// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositorio;

#nullable disable

namespace Repositorio.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241008011005_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dominio.Entidades.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Notebook",
                            Valor = 1500m
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Mouse",
                            Valor = 50m
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Teclado",
                            Valor = 100m
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Monitor",
                            Valor = 200m
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Headset",
                            Valor = 80m
                        },
                        new
                        {
                            Id = 6,
                            Nome = "SSD",
                            Valor = 100m
                        },
                        new
                        {
                            Id = 7,
                            Nome = "RAM",
                            Valor = 50m
                        },
                        new
                        {
                            Id = 8,
                            Nome = "Processador",
                            Valor = 200m
                        },
                        new
                        {
                            Id = 9,
                            Nome = "Placa Mãe",
                            Valor = 120m
                        },
                        new
                        {
                            Id = 10,
                            Nome = "Fonte de Alimentação",
                            Valor = 70m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
